[build]
  command = "yarn build"
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically temp
  
   
 
[[redirects]]
  from = "/blog/*"
  to = "https://llamalife.superblog.cloud/:splat"
  status = 200

[[redirects]]
  from = "/_elderjs/*"
  to = "https://llamalife.superblog.cloud/_elderjs/:splat"
  status = 200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
